# Task 1:

1. Install Jupyter notebook and run the first program and share the screenshot of the output.

In [1]:
print('Hi My Name is Love Varshney')

Hi My Name is Love Varshney

2. Write a program which will find all such numbers which are divisible by 7 but are not a multiple
of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a
comma-separated sequence on a single line.

In [2]:
sequence = []
for i in range(2000,3201):
    if (i%7==0 and i%5!=0):
        sequence.append(i)
print(sequence)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]

3. Write a Python program to accept the user's first and last name and then getting them printed in
the the reverse order with a space between first name and last name

In [3]:
first = input('Please enter your First Name : ')
last = input('Please enter your Last Name : ')
print(first[::-1] + " " + last[::-1])

Please enter your First Name : Love
Please enter your Last Name : Varshney
evoL yenhsraV

4. Write a Python program to find the volume of a sphere with diameter 12 cm.
Formula: V=4/3 * Ï€ * r^3

In [4]:
from math import pi
d=12
r=d/2

V=4/3 * pi * r**3
print(V)

904.7786842338603

# Task 2:

1. Write a program which accepts a sequence of comma-separated numbers from console and
generate a list.

In [5]:
l = input('Please enter  a sequence of comma-separated numbers : ')

l.split(",")

Please enter  a sequence of comma-separated numbers : 1,2,3,4,5

['1', '2', '3', '4', '5']

In [6]:
'''2. Create the below pattern using nested for loop in Python.
  
  *
  * *
  * * *
  * * * *
  * * * * *
  * * * *
  * * *
  * *
  *'''

'2. Create the below pattern using nested for loop in Python.\n  \n  *\n  * *\n  * * *\n  * * * *\n  * * * * *\n  * * * *\n  * * *\n  * *\n  *'

In [7]:
n=5

for i in range(n):
    for j in range(i):
        print("*",end=" ")
    print('')
    
for i in range(n)[::-1]:
    for j in range(i):
        print("*",end=" ")
    print('')

*
* *
* * *
* * * *
* * * *
* * *
* *
*

3. Write a Python program to reverse a word after accepting the input from the user.
Sample Output:
Input word: AcadGild
Output: dilGdacA

In [10]:
word = input('Please enter a word : ')
print('Output : ',word[::-1])

Please enter a word : AcadGild
Output :  dliGdacA

4. Write a Python Program to print the given string in the format specified in the sample output.
WE, THE PEOPLE OF INDIA, having solemnly resolved to constitute India into a
SOVEREIGN, SOCIALIST, SECULAR, DEMOCRATIC REPUBLIC and to secure to all
its citizens

In [11]:
print('WE, THE PEOPLE OF INDIA,\n\thaving solemnly resolved to constitute India into a SOVEREIGN,\n\t\t SOCIALIST, SECULAR, DEMOCRATIC REPUBLIC\n\t\t  and to secure to all its citizens')

WE, THE PEOPLE OF INDIA,
	having solemnly resolved to constitute India into a SOVEREIGN,
		 SOCIALIST, SECULAR, DEMOCRATIC REPUBLIC
		  and to secure to all its citizens